import { LegalPage,LegalSection } from "../legal-document";
import type { ReactNode } from "react";
const L=({children}:{children:ReactNode})=><ul>{children}</ul>;
const sections:LegalSection[]=[
 {title:"Responsable del tratamiento",content:<div className="legal-contact"><strong>Growr360</strong><span>Responsable: JM Iglesias</span><span>Domicilio: Buenos Aires, Argentina</span><a href="mailto:info@growr.com">info@growr.com</a><a href="https://growr360.com">growr360.com</a></div>},
 {title:"Información que podemos recopilar",content:<><p>Según las funciones utilizadas, recopilamos nombre, apellido, correo, identificador, foto, organización, rol, permisos e información técnica necesaria para autenticar y proteger la cuenta. Las contraseñas no se almacenan en texto plano.</p><p>También se registran datos de organizaciones, miembros, invitaciones, solicitudes y actividad administrativa.</p></>},
 {title:"Información agrícola y productiva",content:<><p>Podemos almacenar campos, lotes, superficies, campañas, cultivos, registros, aplicaciones, insumos, monitoreos, adversidades, cosechas, rendimientos, costos, tareas, contratistas, clientes y observaciones.</p><p><strong>Esta información pertenece al usuario o a la organización que la incorpora. Growr360 no adquiere su propiedad.</strong></p></>},
 {title:"Información geográfica",content:<p>Puede incluir GPS, ubicación del dispositivo, coordenadas, polígonos, puntos de monitoreo y recorridos. Se utiliza cuando una función lo requiere y conforme a los permisos del dispositivo.</p>},
 {title:"Archivos geográficos",content:<p>Los archivos KML, KMZ, GeoJSON y otros formatos compatibles se procesan para visualizar campos, delimitar lotes y realizar análisis geográficos.</p>},
 {title:"Fotografías y archivos",content:<p>Las fotos y documentos pueden utilizarse para documentar cultivos, plagas, enfermedades, malezas, daños y actividades. Quien los carga debe contar con autorización cuando incluyan información de terceros.</p>},
 {title:"Imágenes satelitales y datos geoespaciales",content:<p>Para obtener imágenes, NDVI y otros datos derivados puede ser necesario comunicar a proveedores externos la geometría estrictamente necesaria del lote seleccionado.</p>},
 {title:"Información técnica",content:<p>Podemos registrar IP, dispositivo, sistema operativo, versión, navegador, horarios, identificadores, errores, rendimiento y eventos de seguridad para mantener y proteger la plataforma.</p>},
 {title:"Cómo utilizamos la información",content:<L><li>Administrar cuentas, grupos y permisos.</li><li>Gestionar campos, lotes, registros, monitoreos, mapas, imágenes y reportes.</li><li>Sincronizar dispositivos, enviar notificaciones y brindar soporte.</li><li>Detectar errores, prevenir fraude, mejorar el servicio y cumplir obligaciones legales.</li></L>},
 {title:"Datos de una organización",content:<p>La información de una organización es accesible sólo por sus miembros autorizados según rol y permisos. Cuando alguien abandona el grupo pierde ese acceso, aunque sus registros pueden permanecer como parte del historial operativo.</p>},
 {title:"Proveedores tecnológicos",content:<p>Podemos utilizar proveedores de base de datos, autenticación, almacenamiento, hosting, mapas, imágenes satelitales, notificaciones, correo, analítica y pagos. Acceden sólo a la información necesaria para prestar su servicio.</p>},
 {title:"Transferencias internacionales",content:<p>Algunos proveedores pueden procesar datos fuera de Argentina. Procuramos que esas transferencias cumplan las normas aplicables y cuenten con garantías adecuadas.</p>},
 {title:"Venta de información",content:<><p><strong>Growr360 no vende datos personales ni información privada que identifique directamente una explotación agrícola.</strong></p><p>Las estadísticas generales pueden generarse con información agregada o anonimizada.</p></>},
 {title:"Uso de datos para mejorar Growr360",content:<p>Analizamos funcionamiento, rendimiento y uso para corregir errores y mejorar funciones, preferentemente con información agregada, estadística o anonimizada.</p>},
 {title:"Inteligencia artificial y procesamiento automatizado",content:<p>Las funciones automatizadas se informarán cuando corresponda. La incorporación de IA no autoriza por sí sola el uso de datos privados para entrenar modelos de terceros; se solicitará consentimiento adicional cuando sea necesario.</p>},
 {title:"Seguridad",content:<p>Aplicamos autenticación, cifrado, controles de acceso, permisos por organización y medidas técnicas y organizativas razonables. Ningún sistema conectado a Internet puede garantizar seguridad absoluta.</p>},
 {title:"Conservación de información",content:<p>Conservamos datos mientras la cuenta esté activa, sean necesarios para el servicio o historial de la organización, o exista una obligación o razón legítima. Luego pueden eliminarse, anonimizarse o archivarse.</p>},
 {title:"Eliminación de cuenta",content:<p>Eliminar una cuenta personal no elimina automáticamente el historial generado para una organización. Cuando corresponda, la relación con el usuario eliminado puede anonimizarse.</p>},
 {title:"Derechos sobre los datos personales",content:<><p>Los titulares pueden solicitar información, acceso, actualización, rectificación o supresión escribiendo a <a href="mailto:info@growr.com">info@growr.com</a>.</p><p>Podemos requerir datos razonables para verificar la identidad.</p></>},
 {title:"Plazos para solicitudes",content:<p>Las solicitudes de acceso, rectificación, actualización o supresión se responden dentro de los plazos previstos por la legislación aplicable.</p>},
 {title:"Datos de terceros",content:<p>Quien incorpore datos de clientes, empleados, contratistas o productores debe contar con autorización o base legítima suficiente.</p>},
 {title:"Datos sensibles",content:<p>Growr360 no solicita en general datos sensibles. Los usuarios deben evitar cargarlos salvo que sean estrictamente necesarios y exista una base legal adecuada.</p>},
 {title:"Comunicaciones",content:<p>Podemos enviar verificaciones, recuperación de contraseña, alertas de seguridad, invitaciones, notificaciones operativas y avisos importantes. Las comunicaciones promocionales tendrán mecanismos de baja cuando corresponda.</p>},
 {title:"Cookies y almacenamiento local",content:<p>La web puede usar tecnologías necesarias para sesiones, autenticación, configuración, seguridad y análisis técnico. Se solicitará consentimiento cuando la ley lo requiera.</p>},
 {title:"Menores de edad",content:<p>La plataforma está orientada a personas y organizaciones agrícolas. Los menores sólo deben utilizarla con capacidad o autorización suficiente según la ley.</p>},
 {title:"Requerimientos legales",content:<p>Podemos conservar o comunicar información para cumplir obligaciones, órdenes de autoridad, investigar fraude o proteger derechos y seguridad, limitándola a lo necesario.</p>},
 {title:"Cambios en esta Política",content:<p>Las actualizaciones sustanciales se comunicarán mediante la plataforma, correo u otro mecanismo razonable. La fecha vigente se indica al comienzo.</p>},
 {title:"Autoridad de control",content:<p>La Agencia de Acceso a la Información Pública (AAIP) es la autoridad de aplicación de la Ley N.º 25.326 en la República Argentina.</p>},
 {title:"Contacto",content:<div className="legal-contact"><strong>Growr360</strong><span>Responsable: JM Iglesias</span><span>Domicilio: Buenos Aires, Argentina</span><a href="mailto:info@growr.com">info@growr.com</a></div>},
 {title:"Consentimiento y aceptación",content:<p>Cuando un tratamiento requiera consentimiento, se solicitará de forma clara. El usuario puede administrar permisos de ubicación, fotografías y archivos desde su dispositivo.</p>}
];
export default function Privacy(){return <LegalPage active="privacy" eyebrow="ÚLTIMA ACTUALIZACIÓN: 3 DE SEPTIEMBRE DE 2026" title="Privacidad y protección de datos" intro="Explicamos qué información tratamos, para qué la usamos, cómo la protegemos y qué derechos podés ejercer." sections={sections}/>}
