"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { createClient, Session } from "@supabase/supabase-js";
import { Activity, ArrowLeft, BarChart3, Bell, CalendarDays, Check, ChevronRight, CircleAlert, CreditCard, FileText, LayoutDashboard, LoaderCircle, LogOut, Megaphone, RefreshCcw, Save, Search, ShieldCheck, Sprout, Tractor, UserCog, Users, X } from "lucide-react";

const client=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL??"https://emwfdcekpxwzvnidwdls.supabase.co",process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY??"sb_publishable_waHR1lcMgPHyP32KlyBcEw_uAL6n6-g",{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
type Tab="dashboard"|"groups"|"users"|"notifications";
type Dashboard={platform_admin:boolean;groups:number;users:number;active_campaigns:number;records_30d:number;notifications_30d:number;pending_requests:number;free_users:number;pro_users:number;business_users:number};
type AdminGroup={id:string;name:string;description?:string|null;cuit:string;image_path?:string|null;creator_name:string;created_at:string;deleted_at?:string|null;member_count:number;field_count:number;plot_count:number;record_count:number};
type AdminUser={id:string;first_name:string;last_name:string;full_name:string;username:string;email:string;phone?:string|null;avatar_path?:string|null;is_platform_admin:boolean;created_at:string;group_count:number;subscription_plan:"free"|"pro"|"business";subscription_status:"active"|"trialing"|"expired"|"cancelled";subscription_started_at?:string|null;subscription_expires_at?:string|null;memberships:{group_id:string;group_name:string;role:string;status:string}[]};
type GroupDetail={members:{user_id:string;name:string;email:string;role:string;status:string}[];campaigns:{id:string;name:string;start_date:string;end_date:string;status:string}[];pending_requests:{id:string;user_id:string;name:string;email:string;requested_role:string;created_at:string}[];recent_notifications:{id:string;title:string;message:string;priority:string;created_at:string;recipients:number}[]};
const emptyDashboard:Dashboard={platform_admin:false,groups:0,users:0,active_campaigns:0,records_30d:0,notifications_30d:0,pending_requests:0,free_users:0,pro_users:0,business_users:0};

export default function AdminPage(){
 const[session,setSession]=useState<Session|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[tab,setTab]=useState<Tab>("dashboard");
 const[dashboard,setDashboard]=useState(emptyDashboard);const[groups,setGroups]=useState<AdminGroup[]>([]);const[users,setUsers]=useState<AdminUser[]>([]);const[query,setQuery]=useState("");const[selectedGroupId,setSelectedGroupId]=useState("");const[detail,setDetail]=useState<GroupDetail|null>(null);const[busy,setBusy]=useState("");const[message,setMessage]=useState("");
 useEffect(()=>{document.body.classList.add("admin-route-open");document.documentElement.classList.add("admin-route-open");return()=>{document.body.classList.remove("admin-route-open");document.documentElement.classList.remove("admin-route-open")}},[]);
 const load=useCallback(async()=>{setLoading(true);setError("");const[d,g,u]=await Promise.all([client.rpc("admin_console_dashboard"),client.rpc("admin_console_groups",{p_query:""}),client.rpc("admin_console_users",{p_query:""})]);if(d.error){setError(d.error.message);setLoading(false);return}setDashboard((d.data??emptyDashboard)as Dashboard);setGroups((g.data??[])as AdminGroup[]);setUsers((u.data??[])as AdminUser[]);setLoading(false)},[]);
 useEffect(()=>{client.auth.getSession().then(({data})=>{setSession(data.session);if(data.session)void load();else setLoading(false)});const{data}=client.auth.onAuthStateChange((_event,next)=>setSession(next));return()=>data.subscription.unsubscribe()},[load]);
 async function search(){setBusy("search");const fn=tab==="users"?"admin_console_users":"admin_console_groups";const result=await client.rpc(fn,{p_query:query.trim()});setBusy("");if(result.error)setMessage(result.error.message);else if(tab==="users")setUsers((result.data??[])as AdminUser[]);else setGroups((result.data??[])as AdminGroup[])}
 async function openGroup(id:string){setSelectedGroupId(id);setDetail(null);const result=await client.rpc("admin_console_group_detail",{p_group_id:id});if(result.error)setMessage(result.error.message);else setDetail(result.data as GroupDetail)}
 async function refreshDetail(){if(selectedGroupId)await openGroup(selectedGroupId);await load()}
 if(loading)return <AdminLoading/>;
 if(!session)return <AdminAccess title="Iniciá sesión" text="Necesitás una sesión de Growr360 para ingresar al panel."/>;
 if(error)return <AdminAccess title="Acceso restringido" text="No pudimos validar tu acceso al panel global." detail={error}/>;
 if(!dashboard.platform_admin)return <AdminAccess title="Panel global restringido" text="Esta sección pertenece al dueño de la plataforma. La administración de cada grupo se realiza desde Equipo y Configuración del grupo."/>;
 const selected=groups.find(group=>group.id===selectedGroupId)??null;
 return <div className="admin-shell">
  <aside className="admin-sidebar"><AdminBrand/><div className="admin-scope"><ShieldCheck/><div><small>ADMINISTRACIÓN GLOBAL</small><strong>Toda la plataforma</strong></div></div><nav>{([ ["dashboard","Resumen",LayoutDashboard],["groups","Grupos y campañas",Tractor],["users","Usuarios y planes",Users],["notifications","Notificaciones",Bell] ] as const).map(([id,label,Icon])=><button className={tab===id?"active":""} key={id} onClick={()=>{setTab(id);setSelectedGroupId("");setDetail(null);setMessage("")}}><Icon/>{label}<ChevronRight/></button>)}</nav><div className="admin-sidebar-bottom"><a href="/"><ArrowLeft/>Volver a Growr360</a><button onClick={()=>void client.auth.signOut()}><LogOut/>Cerrar sesión</button></div></aside>
  <main className="admin-main"><header className="admin-topbar"><div><span>PANEL ADMINISTRATIVO</span><h1>{tab==="dashboard"?"Seguimiento general":tab==="groups"?"Grupos y campañas":tab==="users"?"Usuarios y accesos":"Centro de notificaciones"}</h1></div><button className="admin-refresh" onClick={()=>void load()}><RefreshCcw/>Actualizar</button></header>{message&&<div className="admin-message"><Check/>{message}<button onClick={()=>setMessage("")}><X/></button></div>}
   {tab==="dashboard"&&<><SubscriptionSummary data={dashboard}/><DashboardView data={dashboard} groups={groups}/></>} 
   {tab==="groups"&&<><AdminSearch value={query} setValue={setQuery} placeholder="Buscar grupo o CUIT…" busy={busy==="search"} submit={search}/><div className="admin-split"><GroupList groups={groups} selected={selectedGroupId} open={openGroup}/><div>{selected&&detail?<GroupManager group={selected} detail={detail} platform={dashboard.platform_admin} busy={busy} setBusy={setBusy} notify={setMessage} refresh={refreshDetail}/>:<AdminEmpty icon={Tractor} title="Seleccioná un grupo" text="Vas a poder editar sus datos, campañas e integrantes."/>}</div></div></>}
   {tab==="users"&&<><AdminSearch value={query} setValue={setQuery} placeholder="Buscar por nombre, usuario o correo…" busy={busy==="search"} submit={search}/><UsersManager users={users} platform={dashboard.platform_admin} busy={busy} setBusy={setBusy} notify={setMessage} refresh={load}/></>}
   {tab==="notifications"&&<NotificationManager groups={groups.filter(group=>!group.deleted_at)} selectedId={selectedGroupId} setSelected={id=>{setSelectedGroupId(id);void openGroup(id)}} detail={detail} busy={busy} setBusy={setBusy} notify={setMessage} refresh={refreshDetail}/>} 
  </main>
 </div>
}

function AdminBrand(){return <div className="admin-brand"><img src="/growr360-logo.png" alt="Growr360"/><div><strong>Growr<span>360</span></strong><small>Administración</small></div></div>}
function AdminLoading(){return <div className="admin-loading"><img src="/growr360-logo.png" alt="Growr360"/><LoaderCircle className="spin"/><strong>Preparando panel administrativo…</strong></div>}
function AdminAccess({title,text,detail}:{title:string;text:string;detail?:string}){return <div className="admin-access"><div><CircleAlert/><h1>{title}</h1><p>{text}</p>{detail&&<small>{detail}</small>}<a href="/"><ArrowLeft/>Volver a Growr360</a></div></div>}
function AdminSearch({value,setValue,placeholder,busy,submit}:{value:string;setValue:(v:string)=>void;placeholder:string;busy:boolean;submit:()=>void}){return <form className="admin-search" onSubmit={(event:FormEvent)=>{event.preventDefault();submit()}}><Search/><input value={value} onChange={e=>setValue(e.target.value)} placeholder={placeholder}/><button disabled={busy}>{busy?<LoaderCircle className="spin"/>:"Buscar"}</button></form>}
function AdminEmpty({icon:Icon,title,text}:{icon:typeof Tractor;title:string;text:string}){return <div className="admin-empty"><Icon/><strong>{title}</strong><p>{text}</p></div>}

function DashboardView({data,groups}:{data:Dashboard;groups:AdminGroup[]}){const max=Math.max(1,...groups.map(group=>group.record_count));return <div className="admin-dashboard"><section className="admin-kpis"><AdminKpi icon={Users} label="Usuarios" value={data.users} note="con acceso activo"/><AdminKpi icon={Tractor} label="Grupos" value={data.groups} note="bajo administración"/><AdminKpi icon={CalendarDays} label="Campañas activas" value={data.active_campaigns} note="en curso"/><AdminKpi icon={Activity} label="Registros" value={data.records_30d} note="últimos 30 días"/><AdminKpi icon={Bell} label="Notificaciones" value={data.notifications_30d} note="últimos 30 días"/><AdminKpi icon={UserCog} label="Solicitudes" value={data.pending_requests} note="pendientes"/></section><section className="admin-panel admin-activity-chart"><header><div><span>ACTIVIDAD POR GRUPO</span><h2>Registros acumulados</h2></div><BarChart3/></header><div>{groups.slice().sort((a,b)=>b.record_count-a.record_count).slice(0,8).map(group=><div key={group.id}><strong>{group.name}</strong><i><b style={{width:`${Math.max(2,group.record_count/max*100)}%`}}/></i><span>{group.record_count}</span></div>)}{!groups.length&&<p>No hay grupos para mostrar.</p>}</div></section><section className="admin-panel admin-attention"><header><div><span>SEGUIMIENTO</span><h2>Atención administrativa</h2></div><CircleAlert/></header><div><article><strong>{data.pending_requests}</strong><span>solicitudes esperan revisión</span></article><article><strong>{groups.filter(group=>!group.description).length}</strong><span>grupos sin descripción institucional</span></article><article><strong>{groups.filter(group=>!group.image_path).length}</strong><span>grupos sin imagen</span></article></div></section></div>}
function AdminKpi({icon:Icon,label,value,note}:{icon:typeof Users;label:string;value:number;note:string}){return <article><div><Icon/></div><span>{label}</span><strong>{value.toLocaleString("es-AR")}</strong><small>{note}</small></article>}
function SubscriptionSummary({data}:{data:Dashboard}){return <section className="admin-plan-summary"><header><div><CreditCard/><span><small>SUSCRIPCIONES</small><strong>Distribución de planes</strong></span></div><p>Los cambios de plan se realizan desde Usuarios y planes.</p></header><div><article className="free"><span>Growr Free</span><strong>{data.free_users.toLocaleString("es-AR")}</strong><small>usuarios</small></article><article className="pro"><span>Growr Pro</span><strong>{data.pro_users.toLocaleString("es-AR")}</strong><small>usuarios</small></article><article className="business"><span>Growr Business</span><strong>{data.business_users.toLocaleString("es-AR")}</strong><small>usuarios</small></article></div></section>}

function GroupList({groups,selected,open}:{groups:AdminGroup[];selected:string;open:(id:string)=>void}){return <div className="admin-group-list">{groups.map(group=><button key={group.id} className={selected===group.id?"active":""} onClick={()=>void open(group.id)}><div className="admin-group-mark">{group.name.slice(0,2).toUpperCase()}</div><div><strong>{group.name}</strong><small>{group.member_count} integrantes · {group.plot_count} lotes</small></div>{group.deleted_at&&<em>Archivado</em>}<ChevronRight/></button>)}{!groups.length&&<AdminEmpty icon={Search} title="Sin resultados" text="No encontramos grupos con esa búsqueda."/>}</div>}

function GroupManager({group,detail,platform,busy,setBusy,notify,refresh}:{group:AdminGroup;detail:GroupDetail;platform:boolean;busy:string;setBusy:(v:string)=>void;notify:(v:string)=>void;refresh:()=>Promise<void>}){
 const[name,setName]=useState(group.name);const[description,setDescription]=useState(group.description??"");const[cuit,setCuit]=useState(group.cuit);const[showCampaign,setShowCampaign]=useState(false);const[campaignName,setCampaignName]=useState("");const[startDate,setStartDate]=useState("");const[endDate,setEndDate]=useState("");
 useEffect(()=>{setName(group.name);setDescription(group.description??"");setCuit(group.cuit)},[group]);
 async function save(){setBusy("group");const result=await client.rpc("admin_console_update_group",{p_group_id:group.id,p_name:name,p_description:description,p_cuit:cuit.replace(/\D/g,""),p_archived:Boolean(group.deleted_at)});setBusy("");if(result.error)notify(result.error.message);else{notify("Datos del grupo actualizados.");await refresh()}}
 async function createCampaign(event:FormEvent){event.preventDefault();setBusy("new-campaign");const result=await client.rpc("admin_console_create_campaign",{p_group_id:group.id,p_name:campaignName.trim(),p_start_date:startDate,p_end_date:endDate});setBusy("");if(result.error)notify(result.error.message);else{setCampaignName("");setStartDate("");setEndDate("");setShowCampaign(false);notify("Campaña creada.");await refresh()}}
 async function campaign(id:string,status:string){setBusy(id);const result=await client.rpc("admin_console_set_campaign",{p_campaign_id:id,p_status:status});setBusy("");if(result.error)notify(result.error.message);else{notify("Campaña actualizada.");await refresh()}}
 async function member(userId:string,nextRole:string,status:string){setBusy(userId);const result=await client.rpc("admin_console_set_member",{p_group_id:group.id,p_user_id:userId,p_role:nextRole,p_status:status});setBusy("");if(result.error)notify(result.error.message);else{notify("Integrante actualizado.");await refresh()}}
 async function resolveRequest(id:string,approve:boolean,requestedRole:string){setBusy(id);const result=await client.rpc("admin_console_resolve_request",{p_request_id:id,p_approve:approve,p_role:requestedRole});setBusy("");if(result.error)notify(result.error.message);else{notify(approve?"Solicitud aprobada.":"Solicitud rechazada.");await refresh()}}
 async function archive(){if(!confirm(group.deleted_at?"¿Reactivar este grupo?":"¿Archivar este grupo? Sus datos no se eliminan."))return;setBusy("archive");const result=await client.rpc("admin_console_update_group",{p_group_id:group.id,p_name:name,p_description:description,p_cuit:cuit.replace(/\D/g,""),p_archived:!group.deleted_at});setBusy("");if(result.error)notify(result.error.message);else{notify(group.deleted_at?"Grupo reactivado.":"Grupo archivado.");await refresh()}}
 return <div className="admin-group-manager">
  <section className="admin-panel admin-group-editor"><header><div><span>DATOS INSTITUCIONALES</span><h2>{group.name}</h2></div><ShieldCheck/></header><div className="admin-form-grid"><label>Nombre<input value={name} onChange={e=>setName(e.target.value)}/></label><label>CUIT<input inputMode="numeric" value={cuit} onChange={e=>setCuit(e.target.value.replace(/\D/g,"").slice(0,11))}/></label><label className="wide">Descripción<textarea value={description} onChange={e=>setDescription(e.target.value)} maxLength={500}/></label></div><footer><button className="admin-primary" disabled={busy==="group"||!name.trim()||cuit.length!==11} onClick={()=>void save()}>{busy==="group"?<LoaderCircle className="spin"/>:<Save/>}Guardar</button>{platform&&<button className="admin-danger" onClick={()=>void archive()}>{group.deleted_at?"Reactivar grupo":"Archivar grupo"}</button>}</footer></section>
  {detail.pending_requests.length>0&&<section className="admin-panel"><header><div><span>SOLICITUDES</span><h2>Ingresos pendientes</h2></div><UserCog/></header><div className="admin-requests">{detail.pending_requests.map(item=><div key={item.id}><div><strong>{item.name||"Usuario"}</strong><small>{item.email} · {role(item.requested_role)}</small></div><button className="admin-reject" disabled={busy===item.id} onClick={()=>void resolveRequest(item.id,false,item.requested_role)}>Rechazar</button><button className="admin-approve" disabled={busy===item.id} onClick={()=>void resolveRequest(item.id,true,item.requested_role)}>Aprobar</button></div>)}</div></section>}
  <section className="admin-panel"><header><div><span>CAMPAÑAS</span><h2>Ciclos productivos</h2></div><button className="admin-add-small" onClick={()=>setShowCampaign(value=>!value)}>{showCampaign?<X/>:<CalendarDays/>}{showCampaign?"Cancelar":"Nueva campaña"}</button></header>{showCampaign&&<form className="admin-new-campaign" onSubmit={createCampaign}><label>Nombre<input required maxLength={30} value={campaignName} onChange={e=>setCampaignName(e.target.value)} placeholder="Ej. 27/28"/></label><label>Inicio<input required type="date" value={startDate} onChange={e=>setStartDate(e.target.value)}/></label><label>Fin<input required type="date" min={startDate} value={endDate} onChange={e=>setEndDate(e.target.value)}/></label><button className="admin-primary" disabled={busy==="new-campaign"}>{busy==="new-campaign"?<LoaderCircle className="spin"/>:"Crear"}</button></form>}<div className="admin-campaigns">{detail.campaigns.map(item=><div key={item.id}><div><strong>{item.name}</strong><small>{date(item.start_date)} — {date(item.end_date)}</small></div><select disabled={busy===item.id} value={item.status} onChange={e=>void campaign(item.id,e.target.value)}><option value="planned">Planificada</option><option value="active">Activa</option><option value="closed">Finalizada</option></select></div>)}{!detail.campaigns.length&&<p>Este grupo todavía no tiene campañas.</p>}</div></section>
  <section className="admin-panel"><header><div><span>INTEGRANTES</span><h2>Roles y estado</h2></div><Users/></header><div className="admin-members">{detail.members.map(item=><div key={item.user_id}><div><strong>{item.name||"Usuario"}</strong><small>{item.email}</small></div>{item.role==="owner"?<span className="owner-badge">Propietario</span>:<><select disabled={busy===item.user_id} value={item.role} onChange={e=>void member(item.user_id,e.target.value,item.status)}><option value="admin">Administrador</option><option value="agronomist">Ingeniero / Agrónomo</option><option value="operator">Operador</option><option value="producer">Productor</option></select><select disabled={busy===item.user_id} value={item.status} onChange={e=>void member(item.user_id,item.role,e.target.value)}><option value="active">Activo</option><option value="suspended">Suspendido</option><option value="rejected">Eliminado</option></select></>}</div>)}</div></section>
 </div>
}

function UsersManager({users,busy,setBusy,notify,refresh}:{users:AdminUser[];platform:boolean;busy:string;setBusy:(v:string)=>void;notify:(v:string)=>void;refresh:()=>Promise<void>}){
 return <div className="admin-users admin-platform-users">{users.map(user=><AdminUserCard key={user.id} user={user} busy={busy} setBusy={setBusy} notify={notify} refresh={refresh}/>)}{!users.length&&<AdminEmpty icon={Users} title="Sin usuarios" text="No encontramos cuentas con esa búsqueda."/>}</div>
}

function AdminUserCard({user,busy,setBusy,notify,refresh}:{user:AdminUser;busy:string;setBusy:(value:string)=>void;notify:(value:string)=>void;refresh:()=>Promise<void>}){
 const[plan,setPlan]=useState(user.subscription_plan||"free");
 const[status,setStatus]=useState(user.subscription_status||"active");
 const[expires,setExpires]=useState(user.subscription_expires_at?user.subscription_expires_at.slice(0,10):"");
 useEffect(()=>{setPlan(user.subscription_plan||"free");setStatus(user.subscription_status||"active");setExpires(user.subscription_expires_at?user.subscription_expires_at.slice(0,10):"")},[user]);
 const key=`user-${user.id}`;
 async function savePlan(){setBusy(key);const result=await client.rpc("admin_console_set_subscription",{p_user_id:user.id,p_plan:plan,p_status:status,p_expires_at:expires?new Date(`${expires}T23:59:59`).toISOString():null});setBusy("");if(result.error)notify(result.error.message);else{notify(`Plan de ${user.full_name||user.username} actualizado a ${planName(plan)}.`);await refresh()}}
 async function toggleAdmin(){setBusy(key);const result=await client.rpc("admin_console_set_platform_admin",{p_user_id:user.id,p_enabled:!user.is_platform_admin});setBusy("");if(result.error)notify(result.error.message);else{notify("Acceso administrativo actualizado.");await refresh()}}
 return <article className="admin-user-plan-card"><div className="admin-user-summary"><div className="admin-user-avatar">{initials(user.full_name||user.username)}</div><div className="admin-user-copy"><div className="admin-user-title"><strong>{user.full_name||user.username}</strong><span className={`admin-plan-badge ${user.subscription_plan}`}>{planName(user.subscription_plan)}</span>{user.is_platform_admin&&<span className="admin-global-badge"><ShieldCheck/>Admin global</span>}</div><small>@{user.username} · {user.email}</small><small>{user.phone||"Sin teléfono"} · Alta {dateTime(user.created_at)}</small><div>{user.memberships.map(item=><span key={`${item.group_id}-${item.role}`}>{item.group_name} · {role(item.role)}</span>)}</div></div><div className="admin-user-meta"><strong>{user.group_count}</strong><small>grupo{user.group_count===1?"":"s"}</small></div></div><div className="admin-subscription-editor"><label>Plan<select value={plan} onChange={event=>setPlan(event.target.value as AdminUser["subscription_plan"])}><option value="free">Growr Free</option><option value="pro">Growr Pro</option><option value="business">Growr Business</option></select></label><label>Estado<select value={status} onChange={event=>setStatus(event.target.value as AdminUser["subscription_status"])}><option value="active">Activo</option><option value="trialing">Prueba</option><option value="expired">Vencido</option><option value="cancelled">Cancelado</option></select></label><label>Vencimiento<input type="date" value={expires} onChange={event=>setExpires(event.target.value)}/><small>Vacío = sin vencimiento</small></label><button className="admin-primary" disabled={busy===key} onClick={()=>void savePlan()}>{busy===key?<LoaderCircle className="spin"/>:<CreditCard/>}Guardar plan</button><button className={user.is_platform_admin?"admin-global-toggle active":"admin-global-toggle"} disabled={busy===key} onClick={()=>void toggleAdmin()}><ShieldCheck/>{user.is_platform_admin?"Quitar admin global":"Dar admin global"}</button></div></article>
}

function NotificationManager({groups,selectedId,setSelected,detail,busy,setBusy,notify,refresh}:{groups:AdminGroup[];selectedId:string;setSelected:(id:string)=>void;detail:GroupDetail|null;busy:string;setBusy:(v:string)=>void;notify:(v:string)=>void;refresh:()=>Promise<void>}){const[title,setTitle]=useState("");const[body,setBody]=useState("");const[priority,setPriority]=useState("normal");async function send(event:FormEvent){event.preventDefault();if(!selectedId)return;setBusy("notification");const result=await client.rpc("admin_console_send_notification",{p_group_id:selectedId,p_title:title.trim(),p_message:body.trim(),p_priority:priority});setBusy("");if(result.error)notify(result.error.message);else{setTitle("");setBody("");notify("Comunicado encolado para envío dentro de la app y por push.");await refresh()}}return <div className="admin-notification-layout"><form className="admin-panel admin-notification-form" onSubmit={send}><header><div><span>NUEVO COMUNICADO</span><h2>Enviar al grupo</h2></div><Megaphone/></header><label>Grupo<select required value={selectedId} onChange={e=>setSelected(e.target.value)}><option value="">Seleccionar grupo…</option>{groups.map(group=><option key={group.id} value={group.id}>{group.name}</option>)}</select></label><label>Título<input required minLength={3} maxLength={100} value={title} onChange={e=>setTitle(e.target.value)} placeholder="Ej. Aviso para el equipo"/></label><label>Mensaje<textarea required minLength={3} maxLength={500} value={body} onChange={e=>setBody(e.target.value)} placeholder="Escribí el comunicado…"/></label><label>Prioridad<select value={priority} onChange={e=>setPriority(e.target.value)}><option value="low">Baja</option><option value="normal">Normal</option><option value="high">Alta</option><option value="critical">Crítica</option></select></label><button className="admin-primary" disabled={busy==="notification"||!selectedId}>{busy==="notification"?<LoaderCircle className="spin"/>:<Bell/>}Enviar notificación</button><small>Se entrega a los integrantes activos. La prioridad alta o crítica utiliza envío push prioritario.</small></form><section className="admin-panel admin-notification-history"><header><div><span>HISTORIAL</span><h2>Comunicaciones recientes</h2></div><FileText/></header>{!selectedId?<AdminEmpty icon={Bell} title="Elegí un grupo" text="El historial se mostrará acá."/>:<div>{detail?.recent_notifications?.map(item=><article key={item.id}><i className={item.priority}/><div><strong>{item.title}</strong><p>{item.message}</p><small>{dateTime(item.created_at)} · {item.recipients||1} destinatario{item.recipients===1?"":"s"}</small></div></article>)}{detail&&!detail.recent_notifications.length&&<p>No hay notificaciones recientes.</p>}</div>}</section></div>}

function date(value:string){return new Date(`${value}T12:00:00`).toLocaleDateString("es-AR")}
function dateTime(value:string){return new Date(value).toLocaleString("es-AR",{dateStyle:"short",timeStyle:"short"})}
function initials(value:string){return value.split(/\s+/).filter(Boolean).slice(0,2).map(part=>part[0]).join("").toUpperCase()||"G"}
function role(value:string){return({owner:"Propietario",admin:"Administrador",agronomist:"Ingeniero / Agrónomo",operator:"Operador",producer:"Productor"}as Record<string,string>)[value]??value}
function planName(value:string){return({free:"Growr Free",pro:"Growr Pro",business:"Growr Business"}as Record<string,string>)[value]??value}
