import { LegalPage,LegalSection } from "../legal-document";
import type { ReactNode } from "react";
const L=({children}:{children:ReactNode})=><ul>{children}</ul>;
const sections:LegalSection[]=[
 {title:"Growr360",content:<><p>Growr360 es una plataforma tecnológica destinada a facilitar la gestión y seguimiento de actividades agrícolas mediante su aplicación móvil, sitio web y servicios asociados.</p><L><li>Permite gestionar campos, lotes, campañas, registros, monitoreos, tareas, gastos, insumos, mapas, archivos geográficos, imágenes satelitales, reportes, equipos y permisos.</li><li>Las funciones disponibles pueden variar según el plan, la versión, la ubicación y los servicios de terceros.</li></L></>},
 {title:"Registro y cuenta",content:<p>Para utilizar determinadas funciones es necesario crear una cuenta con información verdadera, actualizada y completa. Cada usuario debe proteger sus credenciales, responde por la actividad de su cuenta salvo hechos no imputables y debe informar accesos no autorizados a la brevedad.</p>},
 {title:"Grupos y organizaciones",content:<><p>Growr360 permite trabajar en organizaciones con múltiples usuarios. El propietario o administrador puede invitar miembros, asignar roles y permisos, administrar recursos y configurar el grupo.</p><p>La suscripción pertenece al grupo y no a cada usuario. Sus miembros acceden a las funciones disponibles para esa organización, mientras que cada acción continúa limitada por su rol y permisos.</p></>},
 {title:"Información cargada por los usuarios",content:<p>Los usuarios conservan los derechos sobre los datos, límites, campañas, registros, fotografías, costos, tareas y archivos que incorporan. Autorizan su tratamiento técnico únicamente para prestar, mantener, proteger y mejorar el servicio. Growr360 no adquiere su propiedad.</p>},
 {title:"Responsabilidad sobre los datos cargados",content:<p>Quien incorpora información debe contar con los derechos o autorizaciones necesarias. Growr360 puede restringir contenido que viole la ley, derechos de terceros, estos términos o la seguridad de la plataforma.</p>},
 {title:"Información agronómica y toma de decisiones",content:<><p>Growr360 es una herramienta tecnológica de apoyo. Sus estadísticas, mapas, índices, alertas, estimaciones e imágenes tienen carácter informativo.</p><p><strong>No reemplaza el asesoramiento de un ingeniero agrónomo ni de otro profesional competente.</strong> El usuario debe verificar la información crítica antes de tomar decisiones productivas.</p></>},
 {title:"Imágenes satelitales, mapas y geolocalización",content:<p>La cobertura, frecuencia y precisión pueden verse afectadas por nubosidad, resolución, atmósfera, GPS, conectividad y proveedores externos. Los límites mostrados no constituyen mensuras ni determinaciones catastrales.</p>},
 {title:"Planes y suscripciones",content:<p>Growr360 puede ofrecer planes gratuitos y pagos con distintos límites de hectáreas, usuarios, almacenamiento, procesamiento, imágenes, reportes e integraciones. Las condiciones vigentes se informan antes de contratar.</p>},
 {title:"Facturación y renovación",content:<p>Antes de confirmar una contratación se informa precio, impuestos, periodicidad, cargos adicionales y, si corresponde, renovación automática. La cancelación evita renovaciones futuras sin afectar el período ya abonado cuando corresponda.</p>},
 {title:"Cambios de planes y precios",content:<p>Las modificaciones que afecten suscripciones vigentes serán comunicadas con anticipación razonable y no afectarán retroactivamente períodos ya abonados, salvo acuerdo o exigencia legal.</p>},
 {title:"Disponibilidad del servicio",content:<p>Puede haber interrupciones por mantenimiento, actualizaciones, infraestructura, conectividad, proveedores o causas fuera del control razonable de Growr360. Las interrupciones programadas relevantes se comunicarán cuando sea posible.</p>},
 {title:"Servicios de terceros",content:<p>La plataforma utiliza proveedores de nube, base de datos, mapas, imágenes satelitales, procesamiento, autenticación, notificaciones, correo y pagos. Sus cambios o interrupciones pueden afectar determinadas funciones.</p>},
 {title:"Uso permitido",content:<L><li>Usar Growr360 de forma lícita y conforme a estos términos.</li><li>No acceder a cuentas ajenas, vulnerar seguridad, introducir software malicioso, sobrecargar infraestructura ni realizar ingeniería inversa fuera de lo permitido por la ley.</li><li>No copiar, modificar, distribuir o explotar componentes sin autorización.</li></L>},
 {title:"Propiedad intelectual",content:<p>El software, diseño, marca, logotipos y documentación de Growr360 están protegidos. El usuario recibe un derecho limitado, revocable, no exclusivo y no transferible para utilizar el servicio mientras mantenga acceso válido.</p>},
 {title:"Seguridad y copias de información",content:<p>Growr360 aplica medidas técnicas y organizativas razonables, aunque ningún sistema garantiza seguridad o disponibilidad absoluta. La plataforma permite solicitar un respaldo integral de la información; para datos críticos también se recomiendan copias adicionales.</p>},
 {title:"Suspensión de cuentas",content:<p>Una cuenta puede suspenderse por riesgos de seguridad, fraude, acceso no autorizado, incumplimientos graves, falta de pago, actividades ilícitas o requerimientos de autoridad. Cuando sea posible se informará el motivo y cómo resolverlo.</p>},
 {title:"Eliminación de la cuenta",content:<p>El usuario puede solicitarla desde la plataforma o por los canales de contacto. La información perteneciente a una organización puede mantenerse para otros miembros autorizados y ciertos datos conservarse por obligaciones legales, fiscales, contractuales o de seguridad.</p>},
 {title:"Privacidad y datos personales",content:<p>Los datos necesarios para prestar el servicio se tratan conforme a la legislación aplicable y a la Política de Privacidad de Growr360.</p>},
 {title:"Limitaciones técnicas",content:<p>Los resultados dependen de datos del usuario y de terceros. Información incompleta o desactualizada puede producir resultados incorrectos. Nada excluye responsabilidades que no puedan limitarse legalmente.</p>},
 {title:"Modificaciones de la Plataforma",content:<p>Growr360 puede incorporar, modificar o discontinuar funciones para mejorar y mantener el servicio. Los cambios sustanciales en servicios pagos vigentes se comunicarán con anticipación razonable cuando sea posible.</p>},
 {title:"Modificaciones de estos Términos",content:<p>Estos términos pueden actualizarse por cambios legales, técnicos, comerciales o funcionales. Las modificaciones sustanciales se comunicarán por la plataforma, correo u otro medio razonable.</p>},
 {title:"Legislación aplicable",content:<p>Se aplican las leyes de la República Argentina. Se respetan especialmente las normas de defensa del consumidor y las reglas de jurisdicción obligatorias.</p>},
 {title:"Contacto",content:<div className="legal-contact"><strong>Growr360</strong><span>Responsable: JM Iglesias</span><span>Domicilio: Buenos Aires, Argentina</span><a href="mailto:info@growr.com">info@growr.com</a><a href="https://growr360.com">growr360.com</a></div>},
 {title:"Aceptación",content:<p>Al crear una cuenta o utilizar Growr360, el usuario declara haber tenido acceso a estos términos y aceptarlos. Si no está de acuerdo, debe abstenerse de utilizar la plataforma.</p>}
];
export default function Terms(){return <LegalPage active="terms" eyebrow="ÚLTIMA ACTUALIZACIÓN: 3 DE SEPTIEMBRE DE 2026" title="Términos y condiciones de uso" intro="Estas condiciones regulan el acceso y la utilización de Growr360, su aplicación móvil, sitio web y servicios asociados." sections={sections}/>}
